name: ads_frontend_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  page_transition: ^2.0.9
  animated_text_kit: ^4.2.2
  responsive_sizer: ^3.1.1
  flutter_otp_text_field: ^1.1.1
  flutter_slidable: ^3.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

